= Spring REST Docs API 文档 Demo
作者 <31007354@qq.com>
v1.0, 2018-01-30
:toc: left
:toclevels: 3
:toc-title: 目  录
:doctype: book
:icons: font
:operation-curl-request-title: Curl 请求
:operation-httpie-request-title: HTTPie 请求
:operation-http-request-title: Http 请求
:operation-request-parameters-title: 请求参数说明
:operation-request-fields-title: 请求参数说明
:operation-http-response-title: Http 响应
:operation-response-fields-title: Http 响应字段说明
:operation-links-title: 相关链接

[[overview]]
== 1、概要
本文为API说明文档。

API 分两部分，一部分为完全的 RESTFul 风格的 API ，另一部分为普通的 API

API的说明包括：请求方式、请求地址、请求参数说明和响应消息等。

[[overview-response]]
== 2、通用说明

*非 RESTFul API 通用响应消息说明*

|===
| 字段 | 类型 | 解释

| errCode
| int
| 200为成功，401为Token失效，其他为自定义状态

| errMessage
| String
| 响应提示信息

| resp_data
| String
| 响应数据
|===

[[resources-restful]]
== 3、BtcPay RESTFul API

[[resources-restful-user]]
=== 3.1、用户

[[resources-restful-user-login]]
==== 3.1.1、登录

operation::restful-user-login[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-restful-user-register]]
==== 3.1.2、注册

operation::restful-user-register[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-restful-user-modifyUserInfo]]
==== 3.1.3、用户信息修改

operation::restful-user-modifyUserInfo[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-restful-user-modfiyPassword]]
==== 3.1.4、修改密码

operation::restful-user-modfiyPassword[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-restful-user-getUserInfo]]
==== 3.1.5、获取用户信息

operation::restful-user-getUserInfo[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-restful-user-sendEmailCode]]
==== 3.1.6、发送邮件验证码

operation::restful-user-sendEmailCode[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-restful-user-sendSmsCode]]
==== 3.1.7、发送短信验证码

operation::restful-user-sendSmsCode[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-restful-user-settingPwd]]
==== 3.1.8、设置密码

operation::restful-user-settingPwd[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-restful-user-verifyCode]]
==== 3.1.9、验证邮件验证码

operation::restful-user-verifyCode[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-restful-user-verifySmsCode]]
==== 3.1.10、验证短信验证码

operation::restful-user-verifySmsCode[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-restful-user-wallet]]
==== 3.1.11、钱包

operation::restful-user-wallet[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-restful-user-getOrderPageList]]
==== 3.1.12、订单列表

operation::restful-user-getOrderPageList[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-restful-user-getMarketPageList]]
==== 3.1.13、行情列表

operation::restful-user-getMarketPageList[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-restful-payment]]
=== 3.2 、支付

[[resources-restful-payment-getScanInfo]]
==== 3.2.1 、获取订单信息

operation::restful-payment-getScanInfo[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-restful-payment-getScanAuth]]
==== 3.2.2 、支付授权

operation::restful-payment-getScanAuth[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-restful-payment-scanPay]]
==== 3.2.3 、发起支付

operation::restful-payment-scanPay[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-restful-payment-queryAddress]]
==== 3.2.4 、查询地址

operation::restful-payment-queryAddress[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-restful-payment-getRechargePageList]]
==== 3.2.5 、获取充值列表

operation::restful-payment-getRechargePageList[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-restful-withdraw-withdraw]]
==== 3.2.6 、提现

operation::restful-withdraw-withdraw[snippets='request-fields,http-request,http-response,curl-request,httpie-request']

[[resources-general]]
== 4、常规 API


