spring:
  application:
    name: My Project
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    #模板加载的位置
    template-loader-path: classpath:/templates/
    #后缀
    suffix: .ftl
    settings:
      locale: zh_CN
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: 0.##
#  resources:
#    static-locations: classpath:/static/**
server:
  port: 8090

swagger:
  desc: 商户系统接口文档
  enable: true
  token.secret: 4606A998B443848FB88EF66931FE1BD2

logs:
  path: ./logs
  level: debug
#=================== db ===================#
datasource:
  #是否启用数据库模式
  enable: true
  # 使用druid数据源
  driver-class-name: com.mysql.cj.jdbc.Driver
  type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:mysql://paycloud.mysql.rds.aliyuncs.com:3308/paycloudv40?autoReconnect=true&characterEncoding=utf-8&useSSL=false
#  url: jdbc:mysql://127.0.0.1:33061/paycloudv40?autoReconnect=true&characterEncoding=utf-8&useSSL=false
  username: wepay
#  username: developer
  password: NouFQVaUBRdpsRwuadCLo1tskS9cPezr0N/Pq8JVfil+7l/DMxKw+bngWxONRh6Ifx/gFozOFIz873MYuT24Hg==
#  password: POaSmwq8WFJyy5Vz17hkAMOFdPg5iN6sOFfeBEa8p4NYEREkyAjsjU2+8DVQlKS0wPpM4CQRo+zlAqqnE/jMJg==
  # 下面为连接池的补充设置，应用到上面所有数据源中
  # 初始化大小，最小，最大
  initialSize: 1
  minIdle: 3
  maxActive: 20
  # 配置获取连接等待超时的时间
  maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 30000
  validationQuery: select 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  # 打开PSCache，并且指定每个连接上PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  filters: config,stat,wall,slf4j
  #打开慢SQL记录
  logSlowSql: true
  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIRZBw4GXgLYtWS9hc4TbeKrZ7AAJ5+SIBKt0Bv465HzopE4REWc9MZ0E9SIWOeat2BPcwH0uj/WA31BFq2QXq8CAwEAAQ==
#  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALph45TfyRCnDy46j8E1UkSXS1dm66/sW+3u/ZTCkSR0VAzTuxSQZB6Eqca2Su/tKPO8buLm0PvQQkhE7dka5q8CAwEAAQ==
  # 合并多个DruidDataSource的监控数据
  #useGlobalDataSourceStat: true
---

# mybatis configuration
mybatis:
  mapper-locations: classpath:mapper/*.xml

redis:
  enable: true
  host: 127.0.0.1
  port: 6379
  password:
  timeout: 0
  database: 0
  pool:
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0



test:
  name: 123
  age: 123
  filePath: E:/imageFiles/
